[default]
application_name="ousadia-api"
application_description="API responsible for validating NPS data"

default_log_level="INFO"
default_access_log="True"

[test]

[qa]

[prod]
default_access_log="False"
sentry_dsn=""