name: deploy api
on: workflow_dispatch
jobs:
  deploy_api:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Deploy API for ${{ github.ref }} branch"
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Declare variables
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Building image for deploy
        run: cd python-api-project && make image/build VERSION=${{ steps.vars.outputs.sha_short }}

      # - name: Run Migrations
      #   env:
      #     VERSION: ${{ steps.vars.outputs.sha_short }}
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #     DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      #     DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      #     DATABASE_USER: ${{ secrets.DATABASE_USER }}
      #     DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      #   run: cd python-api-project && ./.deploy/migrations.sh

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://${{secrets.HEROKU_API_APP_NAME}}.herokuapp.com/health-check"
          delay: 10
          rollbackonhealthcheckfailed: true
